name: hello-world
on: push
jobs: 
    hello-world-job:
        runs-on: ubuntu-latest
        steps: 
            - name: Check out repository code
              uses: actions/checkout@v4 # allows your workflow to access the contents of your repository
            - run: echo "$(cat hello_world.txt)"

