name: hello-world-python
on: push

permissions:
    contents: read

jobs: 
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Check out repository code
              uses: actions/checkout@v4 # allows your workflow to access the contents of your repository
            - name: Set up Python 3.8
              uses: actions/setup-python@v3
              with:
                python-version: "3.8"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
            - name: Run code
              run: python hello_world.py

